django/conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('uploadmodel.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'InferenceUp Cloud'
admin.site.index_title = 'InferenceUp Cloud'
admin.site.site_title = 'InferenceUp Cloud'

django/uploadmodel/urls.py
from django.urls import path
from uploadmodel.views import (
    IndexView,
    SimulationModelUploadView,
    WandModelUploadView,
    LogsTemplateView,
    SystemLogDetailView,
    ClearDjangoLogAjaxView,
    ClearTaskLogAjaxView,
    ClearAllLogsAjaxView,
    StitchingSimulationModelUploadView,
    InferenceModelUploadView,
    AjaxLoadModelsView,
    InferenceModelsView,
    SimSegmentStitchingPointCloudView,
    WandXYZDisplacementModelUploadView,
    GetStitchedFileView
)

urlpatterns = [
    path('', IndexView.as_view(), name="index"),
    path('simulation/model/upload', SimulationModelUploadView.as_view(), name="simulation_mode_upload"),
    path('wand/model/upload', WandModelUploadView.as_view(), name="wand_mode_upload"),
    path('logs', LogsTemplateView.as_view(), name="logs"),
    path('log/detail', SystemLogDetailView.as_view(), name="log-detail"),
    path('clear/all/logs', ClearAllLogsAjaxView.as_view(), name="clear-all-logs-ajax"),
    path('clear/django/log', ClearDjangoLogAjaxView.as_view(), name="clear-django-log-ajax"),
    path('clear/task/log', ClearTaskLogAjaxView.as_view(), name="clear-task-log-ajax"),
    path('wand/model/upload', WandModelUploadView.as_view(), name="wand_mode_upload"),
    path('stitching/simulation/model/upload', StitchingSimulationModelUploadView.as_view(), name="stitching_simulation_mode_upload"),
    path('inference-model-upload', InferenceModelUploadView.as_view(), name='inference-model-upload'),
    path('get-models-for-network/<int:network_id>/', AjaxLoadModelsView.as_view(), name='get-models-for-network'),
    path('inference-models', InferenceModelsView.as_view(), name="inference-models"),
    path('simulation/segment/stitching/model/upload', SimSegmentStitchingPointCloudView.as_view(), name="simulation_segment_stitching_model_upload"),
    path('wand/xyz-displacement/model/upload', WandXYZDisplacementModelUploadView.as_view(), name="wand_xyz_displacement_mode_upload"),
    path('get-stitched-files/<int:uploaded_model_id>/', GetStitchedFileView.as_view(), name='get_stitched_files'),
]

django/uploadmodel/models.py
from django.db import models

# Create your models here.

django/uploadmodel/forms.py
from django import forms
from utils.constant import NETWORK_MODEL_API, NETWORK_API, NETWORK_MODEL_BY_NETWORK_API
from conf.settings import NNDB_SERVER
from django.utils.translation import gettext_lazy as _
import requests
import logging
import os
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator

logger = logging.getLogger(__name__)

def validate_integer(value):
    if value is not None and not isinstance(value, int):
        raise forms.ValidationError('Please enter a valid integer value.')


def validate_folder_path(value):
    if not os.path.exists(value) or not os.path.isdir(value):
        raise ValidationError('Invalid folder path.')

class UploadWandModelForm(forms.Form):
    
    wand_ip = forms.CharField(
        label='Wand IP',
        widget=forms.TextInput(
        attrs={
            'class': 'form-control', 
            'placeholder': 
            'Example: cm4-3.local'
            }),
        required=False)

    dataset_size = forms.IntegerField(
        label='Dataset Size',
        widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Example: 5'}),
        required=False,
        validators=[validate_integer]
        )

    flash = forms.DecimalField(
        label='Flash',
        widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Example: 0 or 1'}),
        required=False,
        validators=[
            MinValueValidator(0, message='Value must be greater than or equal to 0'),
            MaxValueValidator(1, message='Value must be less than or equal to 1'),
        ],
        initial=0.5
        )
    
    dias = forms.DecimalField(
        label='Dias',
        widget=forms.NumberInput(
        attrs={'class': 'form-control', 'placeholder': 'Example: 0 or 1'}),
        required=False,
        validators=[
            MinValueValidator(0, message='Value must be greater than or equal to 0'),
            MaxValueValidator(1, message='Value must be less than or equal to 1'),
        ],
        initial=1
        )

    input_folder = forms.CharField(
        label=_('Input Folder'),
        widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
        validators=[validate_folder_path], required=True,
        initial='/danbots/data2/data/wand/'
    )

    uploaded_model = forms.ChoiceField(
        label=_('Target Upload Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    depth_model = forms.ChoiceField(
        label=_('Depth Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    wrap_model = forms.ChoiceField(
        label=_('Wrap Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    lum_model = forms.ChoiceField(
        label=_('Lum Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    opa_model = forms.ChoiceField(
        label=_('Opa Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    batch_name = forms.CharField(
        label=_('Batch Name'),
        widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'})
    )
    
    # start = forms.CharField(
    #     label=_('Start'),
    #     max_length=100,
    #     widget=forms.NumberInput(attrs={'class': 'form-control', 'required': 'required', 'step': 1})
    # )
    # stop = forms.CharField(
    #     label=_('Stop'),
    #     max_length=100,
    #     widget=forms.NumberInput(attrs={'class': 'form-control', 'required': 'required', 'step': 1})
    # )
    # step = forms.CharField(
    #     label=_('Step'),
    #     max_length=100,
    #     widget=forms.NumberInput(attrs={'class': 'form-control', 'required': 'required', 'step': 1})
    # )
   
    DEPTH_COMPARISON_CHOICES = [
        ('', 'Please select one type'),
        ('plane', 'Plane'),
        ('sphere', 'Sphere'),
        ('stl', 'STL'),
    ]
    depth_comparison = forms.ChoiceField(
            label=_('Depth comparison type'),
            choices=DEPTH_COMPARISON_CHOICES,
            widget=forms.Select(attrs={'class': 'form-control'})
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.model_data = self.fetch_model_data()
        self.depth_model_data = self.fetch_model_data(parmater="depth")
        self.wrap_model_data = self.fetch_model_data(parmater="wrap")
        self.lum_model_data = self.fetch_model_data(parmater="lum")
        self.opa_model_data = self.fetch_model_data(parmater="opa")
        self.fields['uploaded_model'].choices = self.get_model_choices('id')
        self.fields['depth_model'].choices = self.get_depth_model_choices('model_path', True)
        self.fields['wrap_model'].choices = self.get_wrap_model_choices('model_path', True)
        self.fields['lum_model'].choices = self.get_lum_model_choices('model_path', True)
        self.fields['opa_model'].choices = self.get_opa_model_choices('model_path', True)

    def fetch_model_data(self, parmater=None):
        if parmater:
            if parmater == "depth":
                api_url = NNDB_SERVER + NETWORK_MODEL_API + "?type=depth"
            elif parmater == "wrap":
                 api_url = NNDB_SERVER + NETWORK_MODEL_API + "?type=wrap"
            elif parmater == "lum":
                api_url = NNDB_SERVER + NETWORK_MODEL_API + "?type=lum"
            elif parmater == "opa":
                api_url = NNDB_SERVER + NETWORK_MODEL_API + "?type=opa"
            else:
                api_url = NNDB_SERVER + NETWORK_MODEL_API
        else:
            api_url = NNDB_SERVER + NETWORK_MODEL_API
        try:
            response = requests.get(api_url)
            response.raise_for_status()  # Raise exception if response status code is not 2xx
            return response.json()
        except requests.exceptions.RequestException as e:
            # Handle the exception, e.g., log the error or show a user-friendly message
            logger.exception("Error fetching network models: %s", e)
            return []
    
    def get_model_choices(self, field_name, include_id=False):
        if field_name == 'id':
            name = 'ID'
        else:
            name = "path"
        choices = [('', f'Please select a target model {name}')]
        for model in self.model_data:
            if include_id:
                choice_label = f"{model['id']} - {model[field_name]}"
            else:
                choice_label = model[field_name]
            choices.append((model[field_name], choice_label))
        return choices
    def get_depth_model_choices(self, field_name, include_id=False):
        if field_name == 'id':
            name = 'ID'
        else:
            name = "path"
        choices = [('', f'Please select a depth model {name}')]
        for model in self.depth_model_data:
            if include_id:
                choice_label = f"{model['id']} - {model[field_name]}"
            else:
                choice_label = model[field_name]
            choices.append((model[field_name], choice_label))
        return choices
    def get_wrap_model_choices(self, field_name, include_id=False):
        if field_name == 'id':
            name = 'ID'
        else:
            name = "path"
        choices = [('', f'Please select a wrap model {name}')]
        for model in self.wrap_model_data:
            if include_id:
                choice_label = f"{model['id']} - {model[field_name]}"
            else:
                choice_label = model[field_name]
            choices.append((model[field_name], choice_label))
        return choices
    def get_lum_model_choices(self, field_name, include_id=False):
        if field_name == 'id':
            name = 'ID'
        else:
            name = "path"
        choices = [('', f'Please select a lum model {name}')]
        for model in self.lum_model_data:
            if include_id:
                choice_label = f"{model['id']} - {model[field_name]}"
            else:
                choice_label = model[field_name]
            choices.append((model[field_name], choice_label))
        return choices
    
    def get_opa_model_choices(self, field_name, include_id=False):
        if field_name == 'id':
            name = 'ID'
        else:
            name = "path"
        choices = [('', f'Please select a opa model {name}')]
        for model in self.opa_model_data:
            if include_id:
                choice_label = f"{model['id']} - {model[field_name]}"
            else:
                choice_label = model[field_name]
            choices.append((model[field_name], choice_label))
        return choices
    

class UploadSimulationModelForm(forms.Form):
    input_folder = forms.CharField(
        label=_('Input Folder'),
        widget=forms.TextInput(attrs={'class': 'form-control', 'required': 'required'}),
        validators=[validate_folder_path], required=True,
    )

    uploaded_model = forms.ChoiceField(
        label=_('Target Upload Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    depth_model = forms.ChoiceField(
        label=_('Depth Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    wrap_model = forms.ChoiceField(
        label=_('Wrap Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    lum_model = forms.ChoiceField(
        label=_('Lum Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    opa_model = forms.ChoiceField(
        label=_('Opa Model'),
        widget=forms.Select(attrs={'class': 'form-control', 'required': 'required'})
    )
    batch_name = forms.CharField(
        label=_('Batch Name'),

django/templates/uploadmodel/index.html
{% extends 'base.html' %}
{% block extra_head %}
{% endblock %}
{% load i18n static %}
{% block title %}{% trans "Upload Simulation Model" %}{% endblock %}
{% block content %}
    <div class="card-deck text-center">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">Simulation Model</h5>
            </div>
            <div class="card-body">
                <p class="card-title pricing-card-title">You can upload simulation model from here.</p>
                <a href="{% url 'simulation_mode_upload' %}" class="btn btn-lg btn-block btn-primary">
                    Go
                </a>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">Wand Model</h5>
            </div>
            <div class="card-body">
                <p class="card-title pricing-card-title">You can upload wand model from here.</p>
                <a href="{% url 'wand_mode_upload' %}" class="btn btn-lg btn-block btn-primary">
                   Go
                </a>
            </div>
        </div>
    </div>
    <div class="card-deck text-center">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">Stitching Simulation Model</h5>
            </div>
            <div class="card-body">
                <p class="card-title pricing-card-title">You can upload stitching simulation model from here.</p>
                <a href="{% url 'stitching_simulation_mode_upload' %}" class="btn btn-lg btn-block btn-primary">
                    Go
                </a>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">Inference Model</h5>
            </div>
            <div class="card-body">
                <p class="card-title pricing-card-title">Upload trained models to an inference server here.</p>
                <a href="{% url 'inference-models' %}" class="btn btn-lg btn-block btn-primary">
                    Go
                </a>
            </div>
        </div>
    </div>


    <div class="card-deck text-center">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">Segmentation Stitching Simulation Model</h5>
            </div>
            <div class="card-body">
                <p class="card-title pricing-card-title">You can upload segmentation stitching simulation model from here.</p>
                <a href="{% url 'simulation_segment_stitching_model_upload' %}" class="btn btn-lg btn-block btn-primary">
                    Go
                </a>
            </div>
        </div>
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h5 class="my-0 font-weight-normal">Wand Model Upload 3D Printer</h5>
            </div>
            <div class="card-body">
                <p class="card-title pricing-card-title">You can upload wand model used 3D printer from here.</p>
                <a href="{% url 'wand_xyz_displacement_mode_upload' %}" class="btn btn-lg btn-block btn-primary">
                    Go
                </a>
            </div>
        </div>
    </div>

{% endblock %}
{% block extra_js %}
    <script>

    </script>
{% endblock %}

django/templates/uploadmodel/inference-model-create.html
{% extends 'base.html' %}
{% block extra_head %}
{% endblock %}
{% load i18n static %}
{% block title %}{% trans "Inference Model" %}{% endblock %}
{% block content %}
    <div class="card-deck">
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h5 class="my-0 font-weight-bold">Please update the model info for the inference server</h5>
            </div>
            <div class="card-body">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        {{ form.errors }}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
                
                {% if messages %}
                    {% for message in messages %}
                        {% if  message.tags == "error" %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                {{ message|safe }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% else %}
                            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                                {{ message|safe }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}


                <form method="post" enctype="multipart/form-data" id="upload-inference-model">
                    {% csrf_token %}


                
                    <div class="form-group row">
                        <label for="{{ form.net.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">{{ form.net.label }}</label>
                        <div class="col-sm-9">
                            {{ form.net }}
                            {% if form.net.errors %}
                                <span class="text-danger">{{ form.net.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="{{ form.model.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">
                            {{ form.model.label }}
                        </label>
                        <div class="col-sm-9">
                            {{ form.model }}
                            {% if form.model.errors %}
                                <span class="text-danger">{{ form.model.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    <!--
                    <div class="form-group row">
                        <label for="{{ form.is_currently_used.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">
                            {{ form.is_currently_used.label }}
                        </label>
                        <div class="col-sm-9">
                            {{ form.is_currently_used }}
                            {% if form.is_currently_used.errors %}
                                <span class="text-danger">{{ form.is_currently_used.errors }}</span>
                            {% endif %}
                        </div>
                    </div>
                    -->
                    <div style="text-align: right;">
                        <button type="submit" class="btn btn-primary">Upload</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block extra_js %}
<script>
    $(document).ready(function() {
        $('#id_net').change(function() {
            var netId = $(this).val();
            $.ajax({
                url: '/get-models-for-network/' + netId + '/',
                method: 'GET',
                success: function(data) {
                    $('#id_model').empty().append('<option value="">Please select a model</option>');
                    data.forEach(function(model) {
                        $('#id_model').append(new Option(model[0]+ ' - ' +model[1], model[0]));
                    });
                }
            });
        });
    });
</script>
{% endblock %}

django/templates/uploadmodel/stitching-segment-simulation-create.html
{% extends 'base.html' %}
{% load i18n static %}
{% block title %}{% trans "Segmentation Stitching Simulation Model" %}{% endblock %}
{% block extra_head %}
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock %}
{% block content %}
<div class="card-deck">
    <div class="card mb-4 shadow-sm">
        <div class="card-header">
            <h5 class="my-0 font-weight-bold">Please fill up information about upload segmentation stitching simulation model</h5>
        </div>
        <div class="card-body">
            <!-- Error messages and form start -->
            {% if form.errors %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{ form.errors }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% endif %}
            
            {% if messages %}
                {% for message in messages %}
                    {% if  message.tags == "error" %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert">
                            {{ message|safe }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% else %}
                        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                            {{ message|safe }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data" id="upload-segmented-stitching-simulation-model">
                {% csrf_token %}
                <div class="form-group row">
                    <label for="{{ form.uploaded_model.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">
                        {{ form.uploaded_model.label }}
                    </label>
                    <div class="col-sm-8">
                        {{ form.uploaded_model }}
                        {% if form.uploaded_model.errors %}
                            <span class="text-danger">{{ form.uploaded_model.errors }}</span>
                        {% endif %}
                    </div>
                </div>
            
                <div class="form-group row">
                    <label for="{{ form.stitched_file.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">
                        {{ form.stitched_file.label }}
                    </label>
                    <div class="col-sm-8">
                        {{ form.stitched_file }}
                        {% if form.stitched_file.errors %}
                            <span class="text-danger">{{ form.stitched_file.errors }}</span>
                        {% endif %}
                        <input type="hidden" id="id_stitched_file_required" name="stitched_file_required" value="true" required>
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="{{ form.batch_name.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">{{ form.batch_name.label }}</label>
                    <div class="col-sm-8">
                        {{ form.batch_name }}
                        {% if form.batch_name.errors %}
                            <span class="text-danger">{{ form.batch_name.errors }}</span>
                        {% endif %}
                    </div>
                </div>
            
                <div class="form-group row">
                    <label for="{{ form.nb_points.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">{{ form.nb_points.label }}</label>
                    <div class="col-sm-8">
                        {{ form.nb_points }}
                        {% if form.nb_points.errors %}
                            <span class="text-danger">{{ form.nb_points.errors }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="{{ form.radius.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">{{ form.radius.label }}</label>
                    <div class="col-sm-8">
                        {{ form.radius }}
                        {% if form.radius.errors %}
                            <span class="text-danger">{{ form.radius.errors }}</span>
                        {% endif %}
                    </div>
                </div>
                <div class="form-group row">
                    <label for="{{ form.voxel_size.id_for_label }}" class="col-sm-3 col-form-label font-weight-bold">{{ form.voxel_size.label }}</label>
                    <div class="col-sm-8">
                        {{ form.voxel_size }}
                        {% if form.voxel_size.errors %}
                            <span class="text-danger">{{ form.voxel_size.errors }}</span>
                        {% endif %}
                    </div>
                </div>
                <div style="text-align: right;">
                    <button type="submit" class="btn btn-primary">Execute</button>
                </div>
            </form> 
        </div>
    </div>
</div>
{% endblock %}
{% block extra_js %}
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
<script src="https://rawgit.com/select2/select2-sortable/master/select2.sortable.js"></script>
<script>
$(document).ready(function () {
    var selectedStitchedFiles = [];

    $('#id_stitched_file').select2({
        width: '100%',
        placeholder: 'Select a stitched file',
        allowClear: true,
        tags: true, // Allow user to add custom values
        sorter: function(data) {
            return data; // Disable default sorting
        }
    }).on('select2:select', function (e) {
        var selectedElement = e.params.data;
        selectedStitchedFiles.push(selectedElement.id);
        updateSelectOrder();
        addHiddenField(selectedElement.id, selectedElement.text);
    }).on('select2:unselect', function (e) {
        var unselectedElement = e.params.data;
        var index = selectedStitchedFiles.indexOf(unselectedElement.id);
        if (index > -1) {
            selectedStitchedFiles.splice(index, 1);
        }
        updateSelectOrder();
        removeHiddenField(unselectedElement.id);
    });

    function updateSelectOrder() {
        var $stitched_file = $('#id_stitched_file');
        var options = $stitched_file.find('option');
        options.sort(function(a, b) {
            var aIndex = selectedStitchedFiles.indexOf($(a).val());
            var bIndex = selectedStitchedFiles.indexOf($(b).val());
            return aIndex - bIndex;
        });
        $stitched_file.html(options);
        $stitched_file.val(selectedStitchedFiles).trigger('change');
    }

    function addHiddenField(id, name) {
        var hiddenInput = $('<input>')
            .attr('type', 'hidden')
            .attr('name', 'stitched_file_name_' + id)
            .attr('id', 'stitched_file_name_' + id)
            .val(name);
        $('#upload-segmented-stitching-simulation-model').append(hiddenInput);
    }

    function removeHiddenField(id) {
        $('#stitched_file_name_' + id).remove();
    }

    $('#id_uploaded_model').change(function () {
        var uploadedModelId = $(this).val();
        var $stitched_file = $('#id_stitched_file');
        if (uploadedModelId) {
            $.ajax({
                url: '/get-stitched-files/' + uploadedModelId + '/',
                type: 'GET',
                success: function(data) {
                    $stitched_file.empty();
                    if (data.stitched_file_choices && data.stitched_file_choices.length > 0) {
                        $.each(data.stitched_file_choices, function(index, value) {
                            var option = $('<option></option>').attr('value', value.output_folder).text(value.name || 'No Name');
                            option.data('name', value.name);  // Store additional data in data-* attributes
                            $stitched_file.append(option);
                        });
                    } else {
                        $stitched_file.append($('<option></option>').attr('value', '').text('No stitched files available'));
                    }
                    $stitched_file.trigger('change'); // Refresh Select2
                },
                error: function(xhr, status, error) {
                    console.log('Error fetching stitched files:', error);
                    $stitched_file.append($('<option></option>').attr('value', '').text('Error fetching stitched files'));
                    $stitched_file.trigger('change'); // Refresh Select2
                }
            });
        } else {
            $stitched_file.empty();
            $stitched_file.append($('<option></option>').attr('value', '').text('Select a stitched file'));
            $stitched_file.trigger('change'); // Refresh Select2
        }
    });
});
</script>
{% endblock %}